{{- if and .Values.openvoxview.enabled .Values.openvoxview.ingress.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := ( include "puppetdb.fullname" . ) }}
{{- $servicePort := .Values.openvoxview.port -}}
{{- $pathType := .Values.openvoxview.ingress.pathType | default "ImplementationSpecific" -}}
{{- $apiIsStable := eq (include "puppetserver.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "puppetserver.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "puppetserver.ingress.apiVersion" . }}
kind: Ingress
metadata:
  {{- if .Values.openvoxview.ingress.annotations }}
  annotations:
    {{ toYaml .Values.openvoxview.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.openvoxview.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ template "puppetdb.fullname" . }}-openvoxview
spec:
  {{- if $apiIsStable }}
  {{- if .Values.openvoxview.ingress.ingressClassName }}
  ingressClassName: {{ .Values.openvoxview.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range .Values.openvoxview.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            {{- if and $pathType $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
    {{- end -}}
  {{- if .Values.openvoxview.ingress.tls }}
  tls:
    {{ toYaml .Values.openvoxview.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
